# Numpy Assignment:

# Question: 1 (Solution)

In [6]:
import numpy as np

def generate_vandermonde_matrix(ipvector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return op_matx

inputvector = np.array([1,2,3,4,5])
no_col_opmat = 3
op_matx_dec_order = generate_vandermonde_matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = generate_vandermonde_matrix(inputvector,no_col_opmat,True)

print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")

inputvector = np.array([1,2,4,6,8,10])
no_col_opmat = 5
op_matx_dec_order = gen_vander_matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = gen_vander_matrix(inputvector,no_col_opmat,True)

print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")

The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 



NameError: name 'gen_vander_matrix' is not defined

In [7]:
def find_moving_average(a, n=3):
    
    my_cal = np.cumsum(a, dtype=float) # Return the cumulative sum of the elements along a given axis.
    my_cal[n:] = my_cal[n:] - my_cal[:-n]
    return my_cal[n - 1:] / n

a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(find_moving_average(a, n=3).round(3))

[  5.      4.667   5.667   6.667   9.667  28.667  49.333  72.667  84.
  93.333 116.333]


# Question: 2 (Solution)

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [8]:
X = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
K = 3
N = len(X)
no_of_values = N-K+1
inp = np.array(X)

In [11]:
def func(a,length,number):
    y = []
    for i in np.arange(number):
        y.append(np.average(a[i:i+length]))
    return y

result = func(X,K,no_of_values)
print("The moving average sequence has ",no_of_values,"values")
print("The moving averages with k =",K, "of a ",N,"value sequence is:\n", result )

The moving average sequence has  11 values
The moving averages with k = 3 of a  13 value sequence is:
 [5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
